# Generated by Django 5.1.4 on 2025-04-12 00:04

import django.db.models.deletion
from django.db import migrations, models

from global_app.constants import (
    MINOR,
    MAJOR,
    MEDIUM,
    PENDING,
    COMPLETED,
    POSTPONED,
    IN_PROGRESS,
)


def create_task_process(apps, schema_editor):

    TaskProcess = apps.get_model('task_management', 'TaskProcess')
    TaskProcess.objects.bulk_create([
        TaskProcess(status = PENDING),
        TaskProcess(status = COMPLETED),
        TaskProcess(status = POSTPONED),
        TaskProcess(status = IN_PROGRESS),
    ])

def create_task_status(apps, schema_editor):

    TaskPriority = apps.get_model('task_management', 'TaskPriority')
    TaskPriority.objects.bulk_create([
        TaskPriority(status = MINOR),
        TaskPriority(status = MAJOR),
        TaskPriority(status = MEDIUM),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaskProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_management.taskpriority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.PROTECT, to='task_management.taskprocess'),
        ),
        migrations.RunPython(create_task_process),
        migrations.RunPython(create_task_status),
    ]
